platform :ios, '8.0'
use_frameworks!

target 'DaysTill' do
pod 'AFNetworking', '~> 2.6'
pod 'ORStackView', '~> 3.0'
pod 'SwiftyJSON', '~> 2.3'


pod 'DFramework', :path => 'DaysTillSharedFramework'
end
#/Users/Rachel/Dropbox/Jenkins/DaysTill/DaysTill/DaysTillSharedFramework
